import Head from "next/head";
import styles from "@/styles/Home.module.css";
import React from "react";
import GetUserData from "./components/GetUserData";
import { TODOTASK } from "./interfaces/interface";
import RenderUserData from "./components/RenderUserData";

export default function Home() {
  const [input, setInput] = React.useState<string>("");
  const [todoList, setTodoList] = React.useState<TODOTASK[]>([]);

  const updateInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value);
  };

  const clearInput = () => {
    setInput("");
  };

  const addList = () => {
    if (input.replaceAll(" ", "").length > 0) {
      const newTask: TODOTASK = { todoTask: input };
      setTodoList((pre) => [...pre, newTask]);
      clearInput();
    } else {
      alert("Please fill the field");
    }
  };

  const delList = (delTask: string) => {
    setTodoList(
      todoList.filter((task) => {
        return task.todoTask != delTask;
      })
    );
  };

  const editList = (oldTask: string) => {
    const index = todoList.findIndex((task) => task.todoTask === oldTask);
    const newValue = prompt("Enter a Edit Value.");
    if (index >= 0 && newValue !== null && newValue !== "") {
      const updatedList = [...todoList];
      updatedList[index] = { todoTask: newValue };
      setTodoList(updatedList);
    } else {
      alert("Empty Field is Not Allowed.");
    }
  };

  return (
    <>
      <Head>
        <title>TODO APP - Using NextJS and TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.list}>
          <GetUserData
            input={input}
            updateInput={updateInput}
            addList={addList}
          />
          <RenderUserData
            todoList={todoList}
            delList={delList}
            editList={editList}
          />
        </div>
      </main>
    </>
  );
}
